name: montrex
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <=4.0.0"

dependencies:
  about:
    path: about
  bloc: ^8.1.2
  core:
    path: core
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  http: ^1.1.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  rxdart: ^0.27.7
  sqflite: ^2.3.0

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.3
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - certificates/
